openapi: 3.0.1
info:
  title: Blue Racoon
  description: Provides HTTP interface for DeDrone
  version: "1.3"

servers:
  - url: https://blueracoon.taaja.io/
    description: production
  - url: http://localhost:8090/
    description: local dev
