generator:
  #https://www.freeformatter.com/cron-expression-generator-quartz.html
  interval: "0/15 * * ? * * *"

quarkus:
  http:
    port: 8081
  kafka:
    bootstrap-servers: "46.101.136.244:9092"
    health.enabled: true
mp:
  messgagin:
    incoming:
      generated-sensor:
        topic: "sensor"
        connector: "smallrye-kafka"
        value.deserializer: "io.taaja.blueracoon.jackson.SensorDeserializer"

    outgoing:
      sensor-data-stream:
        connector: "smallrye-kafka"
        topic: "sensor"
        value:
          serializer: "io.quarkus.kafka.client.serialization.JsonbSerializer"

"%dev":
  quarkus:
    http:
      port: 8082

  mp:
    messgagin:
      incoming:
        generated-sensor:
          topic: "sensor"
          connector: "smallrye-kafka"
          value.deserializer: "io.taaja.blueracoon.jackson.SensorDeserializer"

      outgoing:
        sensor-data-stream:
          connector: "smallrye-kafka"
          topic: "sensor"
          value:
            serializer: "io.quarkus.kafka.client.serialization.JsonbSerializer"
