#Server Config
server:
  port: 8080

#App at.kara.carinfra.config
app:
  production: false
  enableDebugController: true

logging:
  level:
    root: info

spring:
  kafka:
    producer:
      bootstrap-servers: 46.101.136.244:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
