app:
  database: "taaja"
  file-buffer: false

kafka:
  bootstrap-servers: "46.101.136.244:9092"

services.purple-tiger:
  timeout: 3000
  url: "https://purpletiger.taaja.io"

quarkus:
  http:
    port: 8090
    cors: true
  mongodb:
    connection-string: mongodb://taaja-mongodb:27017


"%dev":
  app:
    database: "dev-taaja"

  services.purple-tiger:
    url: "http://localhost:8093"

  quarkus:
    mongodb:
      connection-string: mongodb://localhost:27017

"%test":
  app:
    database: "test-taaja"

  quarkus:
    mongodb:
      connection-string: mongodb://localhost:27017